@startmindmap
+ cutopia script:
++ home 
+++ Aboot 
+++ Products
+++ Services
+++ GetStarted
+++ Contact us
++ login
+++ init
++++ docker
++++ folders
++++ subpro
++++ fromrepo
++++++ culampo
++++++ cusmi
++++++ codibarr
++++++ cocalabs
+++ update
+++ upgrade
+++ imigrate
+++ backup
+++ recovry
+++ cycles
+++ clean
+++ remove
@endmindmap

+ cutopia Script
++ About
++ Products
+++ cusmi
+++ culampo
+++ cucalaps
++ Services
+++ Development
++++ New software applications
++++ Custom solutions
+++ Integration
++++ Existing systems
++++ Frameworks
+++ Assistance
++++ Technical support
++++ Troubleshooting
+++ Training
++++ Workshops
++++ Tutorials
+++ Consulting
++++ Strategy
++++ Planning
++ Partnairs
+++ ticenergy
+++ cospc
+++ madorshop
+++ nafissa pro formations
++ Contact us
++ custart
+++ login
+++ Dashboard
++++ Profiles
++++ Projects
+++++ myinit
++++++ 
+++++ mystables
++++++
+++++ mytsts
++++ Cuntracts
++++ PMP
++++ PMC
++++ Blocks
++++ tmp
++++ tst
++++ Archive
++++ logout
+++++ cudit
+++++ cuterm
+++++ cusmi
+++++ codibarr
+++++ culampo
+++++ cucalaps
++++ Services
+++++ Development
++++++ New software applications
++++++ Custom solutions
+++++ Integration
++++++ Existing systems
++++++ Frameworks
+++++ Assistance
++++++ Technical support
++++++ Troubleshooting
+++++ Training
++++++ Workshops
++++++ Tutorials
+++++ Consulting
++++++ Strategy
++++++ Planning
+++ install
+++ update
+++ upgrage
+++ backup
+++ Logout
@endmindmap
