@startmindmap
+ cutopia Script
++ About
+++ help
+++ FAQ
+++ Docs
++ Products
+++ cudit
+++ cuterm
+++ cusmi
+++ codibarr
+++ culampo
+++ cucalaps
++ Services
+++ Development
++++ New software applications
++++ Custom solutions
+++ Integration
++++ Existing systems
++++ Frameworks
+++ Assistance
++++ Technical support
++++ Troubleshooting
+++ Training
++++ Workshops
++++ Tutorials
+++ Consulting
++++ Strategy
++++ Planning
++ Partnairs
+++ ticenergy
+++ cospc
+++ madorshop
+++ nafissa pro formations
++ Contact us
++ custart
+++ login
+++ Dashboard
++++ Profiles
++++ Projects
+++++ myinit
+++++ mystables
+++++ mytsts
++++ Cuntracts
++++ PMP
++++ PMC
++++ Blocks
++++ tmp
++++ tst
++++ Archive
++++ logout
+++++ cudit
+++++ cuterm
+++++ cusmi
+++++ codibarr
+++++ culampo
+++++ cucalaps
++++ Services
+++++ Development
++++++ New software applications
++++++ Custom solutions
+++++ Integration
++++++ Existing systems
++++++ Frameworks
+++++ Assistance
++++++ Technical support
++++++ Troubleshooting
+++++ Training
++++++ Workshops
++++++ Tutorials
+++++ Consulting
++++++ Strategy
++++++ Planning
+++ install
+++ update
+++ upgrage
+++ backup
+++ Logout
@endmindmap
